// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;

namespace CloudIntegration.Models.Cloud
{
    public partial class Accordion : BaseComponent
    {
        public const string Codename = "accordion";
        public const string AccordionItemsCodename = "accordion_items";
        public const string DescriptionCodename = "description";

        public IEnumerable<AccordionItem> AccordionItems { get; set; }
        public string Description { get; set; }
    }
}