// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace KenticoKontentModels
{
    public partial class AnswerTextOnly
    {
        public const string Codename = "answer__text_only_";
        public const string AnswerCodename = "answer";
        public const string IncorrectFeedbackCodename = "incorrect_feedback";
        public const string IsThisACorrectAnswerCodename = "is_this_a_correct_answer_";

        public string Answer { get; set; }
        public string IncorrectFeedback { get; set; }
        public IEnumerable<IMultipleChoiceOption> IsThisACorrectAnswer { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}