// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace CloudIntegration.Models.Cloud
{
    public partial class AnswerCode
    {
        public const string Codename = "answer__code_";
        public const string IncorrectFeedbackCodename = "incorrect_feedback";
        public const string TitleCodename = "title";
        public const string AvailableLanguagesLanguageCodename = "available_languages__language";
        public const string IsThisAnswerCorrectCodename = "is_this_answer_correct_";
        public const string CodeCodename = "code";

        public string IncorrectFeedback { get; set; }
        public string Title { get; set; }
        public IEnumerable<MultipleChoiceOption> AvailableLanguagesLanguage { get; set; }
        public IEnumerable<MultipleChoiceOption> IsThisAnswerCorrect { get; set; }
        public string Code { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}