// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace CloudIntegration.Models.Cloud
{
    public partial class AnswerTextOnly
    {
        public const string Codename = "answer__text_only_";
        public const string IncorrectFeedbackCodename = "incorrect_feedback";
        public const string IsThisACorrectAnswerCodename = "is_this_a_correct_answer_";
        public const string AnswerCodename = "answer";

        public string IncorrectFeedback { get; set; }
        public IEnumerable<MultipleChoiceOption> IsThisACorrectAnswer { get; set; }
        public string Answer { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}