// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace CloudIntegration.Models.Cloud
{
    public partial class Blank
    {
        public const string Codename = "blank";
        public const string BasecomponentDisplayTitleCodename = "basecomponent__display_title";
        public const string BasecomponentIsOptionalCodename = "basecomponent__is_optional_";
        public const string BasecomponentLayoutCodename = "basecomponent__layout";
        public const string BasecomponentCourseVersionCodename = "basecomponent__course_version";
        public const string BasecomponentIncludeInProgressCodename = "basecomponent__include_in_progress_";
        public const string BasecomponentComponentClassesCodename = "basecomponent__component_classes";
        public const string BasecomponentTitleCodename = "basecomponent__title";
        public const string BasecomponentInstructionsCodename = "basecomponent__instructions";

        public string BasecomponentDisplayTitle { get; set; }
        public IEnumerable<MultipleChoiceOption> BasecomponentIsOptional { get; set; }
        public IEnumerable<MultipleChoiceOption> BasecomponentLayout { get; set; }
        public IEnumerable<MultipleChoiceOption> BasecomponentCourseVersion { get; set; }
        public IEnumerable<MultipleChoiceOption> BasecomponentIncludeInProgress { get; set; }
        public IEnumerable<TaxonomyTerm> BasecomponentComponentClasses { get; set; }
        public string BasecomponentTitle { get; set; }
        public string BasecomponentInstructions { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}