// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace CloudIntegration.Models.Cloud
{
    public partial class Block
    {
        public const string Codename = "block";
        public const string DisplayTitleCodename = "display_title";
        public const string BodyCodename = "body";
        public const string CourseVersionVersionCodename = "course_version__version";
        public const string TitleCodename = "title";
        public const string ComponentsCodename = "components";

        public string DisplayTitle { get; set; }
        public string Body { get; set; }
        public IEnumerable<MultipleChoiceOption> CourseVersionVersion { get; set; }
        public string Title { get; set; }
        public IEnumerable<object> Components { get; set; }
        public ContentItemSystemAttributes System { get; set; }
        public int TrackingId { get; set; }
    }
}