// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace CloudIntegration.Models.Cloud
{
    public partial class Graphic : BaseComponent
    {
        public const string Codename = "graphic";
        public const string SmallImageCodename = "small_image";
        public const string AltCodename = "alt";
        public const string AttributionCodename = "attribution";
        public const string LargeImageCodename = "large_image";

        public IEnumerable<Asset> SmallImage { get; set; }
        public string Alt { get; set; }
        public string Attribution { get; set; }
        public IEnumerable<Asset> LargeImage { get; set; }
    }
}