// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using CloudIntegration.Models;
using Kentico.Kontent.Delivery.Abstractions;

namespace KenticoKontentModels
{
    public partial class MultipleChoiceQuestionWithCode : BaseComponent
    {
        public const string Codename = "multiple_choice_question__with_code_";
        public const string AnswersCodename = "answers";
        public const string BasecomponentComponentClassesCodename = "basecomponent__component_classes";
        public const string BasecomponentCourseVersionCodename = "basecomponent__course_version";
        public const string BasecomponentDisplayTitleCodename = "basecomponent__display_title";
        public const string BasecomponentIncludeInProgressCodename = "basecomponent__include_in_progress_";
        public const string BasecomponentInstructionsCodename = "basecomponent__instructions";
        public const string BasecomponentIsOptionalCodename = "basecomponent__is_optional_";
        public const string BasecomponentLayoutCodename = "basecomponent__layout";
        public const string BasecomponentTitleCodename = "basecomponent__title";
        public const string FeedbackIfCorrectCodename = "feedback_if_correct";
        public const string FeedbackIfIncorrectCodename = "feedback_if_incorrect";
        public const string FeedbackIfPartlyCorrectCodename = "feedback_if_partly_correct";
        public const string FeedbackTitleCodename = "feedback_title";
        public const string QuestionTextCodename = "question_text";

        public IEnumerable<AnswerCode> Answers { get; set; }
        public IEnumerable<ITaxonomyTerm> BasecomponentComponentClasses { get; set; }
        public IEnumerable<IMultipleChoiceOption> BasecomponentCourseVersion { get; set; }
        public string BasecomponentDisplayTitle { get; set; }
        public IEnumerable<IMultipleChoiceOption> BasecomponentIncludeInProgress { get; set; }
        public string BasecomponentInstructions { get; set; }
        public IEnumerable<IMultipleChoiceOption> BasecomponentIsOptional { get; set; }
        public IEnumerable<IMultipleChoiceOption> BasecomponentLayout { get; set; }
        public string BasecomponentTitle { get; set; }
        public string FeedbackIfCorrect { get; set; }
        public string FeedbackIfIncorrect { get; set; }
        public string FeedbackIfPartlyCorrect { get; set; }
        public string FeedbackTitle { get; set; }
        public string QuestionText { get; set; }
        public override IContentItemSystemAttributes System { get; set; }
    }
}