// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace CloudIntegration.Models.Cloud
{
    public partial class NarrativeCode : BaseComponent
    {
        public const string Codename = "narrative_code";
        public const string NarrativeCodeItemsCodename = "narrative_code_items";
        public const string SmallInstructionsCodename = "small_instructions";
        public const string RequireAllCodeBeSeeCodename = "require_all_code_be_see_";
        public const string IntroCodename = "intro";

        public IEnumerable<NarrativeCodeItem> NarrativeCodeItems { get; set; }
        public string SmallInstructions { get; set; }
        public IEnumerable<MultipleChoiceOption> RequireAllCodeBeSee { get; set; }
        public string Intro { get; set; }
    }
}