// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace CloudIntegration.Models.Cloud
{
    public partial class NarrativeCodeItem
    {
        public const string Codename = "narrative_code_item";
        public const string TextCodename = "text";
        public const string AvailableLanguagesLanguageCodename = "available_languages__language";
        public const string CodeCodename = "code";
        public const string TitleCodename = "title";

        public string Text { get; set; }
        public IEnumerable<MultipleChoiceOption> AvailableLanguagesLanguage { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}