// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace CloudIntegration.Models.Cloud
{
    public partial class Package
    {
        public const string Codename = "package";
        public const string PagesCodename = "pages";
        public const string DescriptionCodename = "description";
        public const string CourseIdCodename = "course_id";
        public const string CourseVersionVersionCodename = "course_version__version";
        public const string ScoreToPassCodename = "score_to_pass";
        public const string NarrativeNavigationPlacementCodename = "narrative_navigation_placement";
        public const string DisplayTitleCodename = "display_title";
        public const string LanguageCodename = "language";
        public const string BodyCodename = "body";
        public const string CourseNameCodename = "course_name";

        public IEnumerable<Page> Pages { get; set; }
        public string Description { get; set; }
        public string CourseId { get; set; }
        public IEnumerable<MultipleChoiceOption> CourseVersionVersion { get; set; }
        public decimal? ScoreToPass { get; set; }
        public IEnumerable<MultipleChoiceOption> NarrativeNavigationPlacement { get; set; }
        public string DisplayTitle { get; set; }
        public IEnumerable<MultipleChoiceOption> Language { get; set; }
        public string Body { get; set; }
        public string CourseName { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}