// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace KenticoKontentModels
{
    public partial class Section
    {
        public const string Codename = "section";
        public const string BlocksCodename = "blocks";
        public const string BodyCodename = "body";
        public const string DisplayTitleCodename = "display_title";
        public const string TitleCodename = "title";

        public IEnumerable<Block> Blocks { get; set; }
        public string Body { get; set; }
        public string DisplayTitle { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public string Title { get; set; }
    }
}