// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.


using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace CloudIntegration.Models.Components
{
    public partial class TextComponent : IBaseComponent
    {
        public const string Codename = "text_component";
        public const string BasecomponentDisplayTitleCodename = "basecomponent__display_title";
        public const string BasecomponentLayoutCodename = "basecomponent__layout";
        public const string BasecomponentTitleCodename = "basecomponent__title";
        public const string BodyCodename = "body";
        public const string BasecomponentInstructionsCodename = "basecomponent__instructions";

        public string BasecomponentDisplayTitle { get; set; }
        public IEnumerable<MultipleChoiceOption> BasecomponentLayout { get; set; }
        public string BasecomponentTitle { get; set; }
        public string Body { get; set; }
        public string BasecomponentInstructions { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}