// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace CloudIntegration.Models
{
    public partial class Blank : BaseComponent
    {
        public const string Codename = "blank";
        public const string ComponentClassesCodename = "component_classes";
        public const string LayoutCodename = "layout";

        public IEnumerable<TaxonomyTerm> ComponentClasses { get; set; }
        public IEnumerable<MultipleChoiceOption> Layout { get; set; }
    }
}