// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using KenticoCloud.Delivery;

namespace CloudIntegration.Models
{
    public partial class Component
    {
        public const string Codename = "component";
        public const string TitleCodename = "title";
        public const string BodyCodename = "body";

        public string Title { get; set; }
        public string Body { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}