// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using KenticoCloud.Delivery;

namespace CloudIntegration.Models
{
    public partial class CourseMetadata
    {
        public const string Codename = "course_metadata";
        public const string CourseNameCodename = "course_name";

        public string CourseName { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}