// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace CloudIntegration.Models
{
    public partial class Package
    {
        public const string Codename = "package";
        public const string PagesCodename = "pages";
        public const string CourseNameCodename = "course_name";

        public IEnumerable<object> Pages { get; set; }
        public string CourseName { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}