// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).

namespace CloudIntegration.Models
{
    public partial class Text : BaseComponent
    {
        public const string Codename = "text";
        public const string BodyCodename = "body";

        public string Body { get; set; }
    }
}