// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace CloudIntegration.Models
{
    public partial class Text : BaseComponent
    {
        public const string Codename = "text";
        public const string BodyCodename = "body";

        public IEnumerable<TaxonomyTerm> BasecomponentCompontentClasses { get; set; }
        public string Body { get; set; }
    }
}