// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace CloudIntegration.Models
{
    public partial class Video : BaseComponent
    {
        public const string Codename = "video";
        public const string SetCompletionOnCodename = "set_completion_on";
        public const string VideoFileCodename = "videofile";
        public const string DescriptionCodename = "description";
        public const string TranscriptCodename = "transcript";
        public const string LoadingImageCodename = "loading_image";

        public IEnumerable<MultipleChoiceOption> SetCompletionOn { get; set; }
        public IEnumerable<Asset> VideoFile { get; set; }
        public string Description { get; set; }
        public string Transcript { get; set; }
        public IEnumerable<TaxonomyTerm> BasecomponentCompontentClasses { get; set; }
        public IEnumerable<Asset> LoadingImage { get; set; }
    }
}